### ISSUE TITLE
有關於getSession

### ISSUE THREAD

**Issue by jaydennis01** [reanox/MapleStory-v113-Server-Simulator#25]
我是使用NetBeans IDE 8.2 來編譯
但是有關於使用getSession 這明令都會有紅色驚嘆號
還有就是MapleClient 裡面的這段 import io.netty.channel.Channel; 也是紅色驚嘆號
這是哪邊出問題 謝謝弧大

**Comment by jaydennis01** [comment]
大大 我白癡 我弄好了 我知道你心裡一定給我87這兩個字= =

**Comment by reanox** [comment]
JAR庫請記得
